FROM python:3.6.9

#ENV CELERY_BROKER_URL amqp://guest:guest@rabbit:5672//
#ENV CELERY_RESULT_BACKEND redis://redis:6379/0

COPY . /worker
WORKDIR /worker

RUN pip install -r requirements.txt
#ENTRYPOINT celery -A tasks worker --loglevel=info
