version: '3.7'
services:
    web:
        image: logeshkrishnan/flask_k8:latest
        build:
          context: ./api
          dockerfile: Dockerfile
        ports:
            - "5001:5001"
        # depends_on:
        #     - redis
        #     - rabbit
        environment:
            - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672//
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
            - C_FORCE_ROOT=true
            - HOST=0.0.0.0
            - PORT=5001
            - DEBUG=true
        command: gunicorn --bind 0.0.0.0:5001 app:flask_app
        # volumes line used for hot code reloading
        # volumes: ['./api:/api']
    worker:
        image: logeshkrishnan/worker_k8:latest
        build:
            context: ./celery
            dockerfile: dockerfile
        # depends_on:
        #     - rabbit
        #     - redis
        environment:
            - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672//
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        entrypoint: celery -A tasks worker --loglevel=info
        #volumes: ['./worker:/api']
    rabbit:
        hostname: rabbit
        image: rabbitmq:3.8.19
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        ports:
            - "5672:5672"
    redis:
        image: redis
        ports:
         - "6379:6379"

